### ISSUE TITLE
TeamAdminController: Deprecated route (+ uncommented route in routing.yml)

### ISSUE THREAD

**Issue by alexaoh** [vektorprogrammet/vektorprogrammet#1448] opened 2020-10-14 15:54 UTC
Deprecated route in annotations of showAction in TeamAdminController. Also, a route that calls on showAction is uncommented in routing.yml. This could be used instead of the routing in the annotations in the controller?

**Comment by Lundli** [comment] 2020-10-29 09:01
Duplicate of #1430

**Closed by Lundli** 2020-10-29 09:01 UTC
Labels: Code Quality, Deprecation
